node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'NodeJS') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'ae5596db-c1d3-4b8e-9c7a-cc29d0c296ee') {
       def app = docker.build("yanivomc/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
   stage('docker run') {
     sh label: '', script: '''docker run -tid --name docker_test -p 3000 yanivomc/docker-nodejs-demo:${commit_id}
      docker kill docker_test
      '''
     }
   }

