# Use the official Microsoft .NET SDK image to build the application
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy csproj and restore any dependencies
COPY *.csproj ./
RUN dotnet restore

# Copy the rest of the files and build
COPY . ./
RUN dotnet publish -c Release -o out

# Generate the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
ENV PROJECTNAME=ServicesSchedulerLib
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "ServicesSchedulerLib.dll"]
