   stage('step pre') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"
     commit_id = readFile('.git/commit-id').trim()
   }

   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir("basics") {
         sh 'npm install --only=dev'
         sh 'npm test'
       }
     }
   }

   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', "${docker_login}") {
       def app = docker.build("${docker_image}:${commit_id}", '.')
       app.push()
     }
   }

   stage('docker run') {
     try {
       sh "docker run --rm -tid --init --name docker-nodejs-demo -p 3000 ${docker_image}:${commit_id}"
       sleep 10 // Wait for the container to initialize
       sh 'docker ps -a' // Check running containers
       sh 'docker kill docker-nodejs-demo'
     } catch (Exception e) {
       echo "Failed to kill the container: ${e.getMessage()}"
     } finally {
       // Ensure cleanup
       sh 'docker rm -f docker-nodejs-demo || true'
     }
   }
}
