# Use the official Microsoft .NET SDK image to build the application
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy csproj and restore any dependencies
COPY *.csproj ./
RUN dotnet restore

# COPY DLL from required builds - 
# image TypeExtensions
COPY --from=eldan/type-extensions /app/TypeExtensions.dll /app/out/
# Copy the rest of the files and build
COPY . ./
RUN dotnet publish -c Release -o out

# Upload artifacts to nexus

# Generate the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
ENV PROJECTNAME=FlexibleCloner
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "FlexibleCloner.dll"]
