# Use the official Microsoft .NET SDK image to build the application
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy csproj and restore any dependencies
COPY . ./
RUN dotnet restore

# COPY DLL from required builds - 
# image TypeExtensions
# COPY --from=eldan/type-extensions /app/TypeExtensions.dll /app/out/
# Copy the rest of the files and build
RUN dotnet publish -c Release -o out

# # Generate nuget package
# # NOTE! Assuming you have a .nuspec file in OUR project directory
# # Replace 'YourPackageName' with your actual package name and '1.0.0' with your package version
ARG BUILD_NUMBER
RUN dotnet pack /p:PackageVersion=$BUILD_NUMBER -o nugets




# # Upload artifacts to nexus
ARG NEXUS_API_KEY
RUN echo "NEXUS_API_KEY=$NEXUS_API_KEY"
RUN dotnet nuget push "nugets/*.nupkg" --api-key $NEXUS_API_KEY --source "https://eldan-repo.devopshift.com/nexus/repository/nuget-hosted/"


# # Generate the runtime image
# FROM mcr.microsoft.com/dotnet/aspnet:6.0
# ENV PROJECTNAME=LoggerBase
# WORKDIR /app
# COPY --from=build-env /app/out .
# ENTRYPOINT ["dotnet", "LoggerBase.dll"]
